export type SemanticConceptDefinition = {
  label: { ro: string; en: string };
  example: { ro: string; en: string };
  terms: readonly string[];
};

function concept(
  labelRo: string,
  labelEn: string,
  exampleRo: string,
  exampleEn: string,
  terms: readonly string[],
): SemanticConceptDefinition {
  return {
    label: { ro: labelRo, en: labelEn },
    example: { ro: exampleRo, en: exampleEn },
    terms,
  };
}

export const SEMANTIC_CONCEPTS = {
  bleeding: concept("sângerare", "bleeding", "Încă sângerează", "It is still bleeding", [
    "sangereaza",
    "sangerare",
    "curge sange",
    "bleeding",
    "still bleeding",
  ]),
  bleeding_stopped: concept(
    "sângerare oprită",
    "bleeding stopped",
    "S-a oprit la presiune",
    "It stopped with pressure",
    ["se opreste", "s a oprit", "sangerarea s a oprit", "stops", "stopped"],
  ),
  dirty_object: concept(
    "obiect murdar",
    "dirty object",
    "A fost un obiect murdar",
    "It was a dirty object",
    ["obiect murdar", "murdar", "dirty object", "dirty"],
  ),
  rust: concept("rugina", "rust", "Obiectul era ruginit", "The object was rusty", [
    "ruginit",
    "rugina",
    "rusty",
    "rust",
  ]),
  glass: concept("ciob", "glass", "A fost un ciob", "It was glass", [
    "ciob",
    "sticla",
    "glass",
    "shard",
  ]),
  bite: concept("muscatura", "bite", "Este o muscatura", "It is a bite", [
    "muscatura",
    "m a muscat",
    "bite",
    "bitten",
  ]),
  swelling: concept("umflare", "swelling", "Este puțin umflat", "It looks slightly swollen", [
    "umflare",
    "umflatura",
    "umflat",
    "s a umflat",
    "inflamat",
    "swelling",
    "swollen",
  ]),
  bruising: concept("vânătaie", "bruising", "Are o vânătaie", "There is a bruise", [
    "vanataie",
    "vanat",
    "invinetit",
    "echimoza",
    "bruising",
    "bruise",
    "bruised",
  ]),
  deformity: concept("poziție neobișnuită", "unusual position", "Pare strâmb", "It looks crooked", [
    "stramb",
    "pozitie neobisnuita",
    "deformat",
    "deformare",
    "crooked",
    "unusual position",
    "deformity",
    "deformed",
  ]),
  tingling: concept("furnicături", "tingling", "Am furnicături", "I have tingling", [
    "furnicaturi",
    "intepaturi",
    "ace",
    "tingling",
    "pins and needles",
  ]),
  numbness: concept("amorțeală", "numbness", "Am amorțeală", "It feels numb", [
    "amorteala",
    "amortit",
    "nu simt",
    "numbness",
    "numb",
    "cannot feel",
    "can t feel",
  ]),
  weakness: concept("slăbiciune", "weakness", "Simt slăbiciune", "I feel weakness", [
    "slabiciune",
    "fara putere",
    "weakness",
    "weak",
  ]),
  sensation_normal: concept(
    "sensibilitate normală",
    "normal sensation",
    "Nu simt nimic neobișnuit",
    "Sensation feels normal",
    [
      "simt normal",
      "simt bine",
      "sensibilitate normala",
      "nu simt nimic neobisnuit",
      "nimic neobisnuit",
      "feels normal",
      "normal sensation",
      "nothing unusual",
    ],
  ),
  movement_normal: concept(
    "mișcare normală",
    "normal movement",
    "Pot mișca normal",
    "I can move normally",
    [
      "normal",
      "pot normal",
      "pot misca",
      "pot sa misc",
      "misc normal",
      "pot sprijini",
      "merg normal",
      "can move",
      "move normally",
      "can bear weight",
      "walk normally",
    ],
  ),
  movement_partial: concept(
    "mișcare parțială",
    "partial movement",
    "Pot mișca puțin",
    "I can move it a little",
    [
      "partial",
      "pot putin",
      "misc putin",
      "doare cand misc",
      "durere la miscare",
      "a little",
      "partially",
      "hurts when moving",
      "pain when moving",
    ],
  ),
  movement_none: concept("fără mișcare", "no movement", "Nu pot mișca", "I cannot move it", [
    "nu pot",
    "nu pot misca",
    "nu pot sa misc",
    "nu pot sprijini",
    "nu pot merge",
    "deloc",
    "cannot move",
    "can t move",
    "cannot bear weight",
    "cannot walk",
  ]),
  fall: concept("căzătură", "fall", "Am căzut", "I fell", [
    "cazatura",
    "cadere",
    "am cazut",
    "m am impiedicat",
    "am alunecat",
    "fall",
    "fell",
    "tripped",
    "slipped",
  ]),
  impact: concept("lovitură", "impact", "M-am lovit", "I was hit", [
    "lovitura",
    "m am lovit",
    "impact",
    "ciocnire",
    "accident",
    "hit",
    "struck",
    "collision",
  ]),
  effort: concept("efort", "exertion", "A aparut dupa efort", "It started after exertion", [
    "efort",
    "dupa sala",
    "sala",
    "sport",
    "antrenament",
    "ridicat greutati",
    "exertion",
    "exercise",
    "workout",
    "lifting",
  ]),
  repetitive_effort: concept(
    "suprasolicitare repetitivă",
    "repetitive overuse",
    "După mișcări repetitive",
    "After repetitive movement",
    [
      "efort repetitiv",
      "miscari repetitive",
      "suprasolicitare",
      "repetitive effort",
      "repeated movement",
      "overuse",
    ],
  ),
  blisters: concept("bășici", "blisters", "Au apărut bășici", "There are blisters", [
    "basica",
    "basici",
    "flictena",
    "flictene",
    "blister",
    "blisters",
  ]),
  deep_injury: concept("aspect profund", "deep appearance", "Pare profunda", "It looks deep", [
    "adanc",
    "adanca",
    "profund",
    "profunda",
    "deep",
    "gaping",
  ]),
  sensitive_area: concept("zona sensibila", "sensitive area", "Este pe mana", "It is on the hand", [
    "pe fata",
    "pe mana",
    "pe articulatie",
    "langa ochi",
    "face",
    "hand",
    "joint",
    "near the eye",
    "near an eye",
  ]),
  sudden_onset: concept("debut brusc", "sudden onset", "A aparut brusc", "It started suddenly", [
    "brusc",
    "dintr o data",
    "subit",
    "sudden",
    "suddenly",
    "all of a sudden",
  ]),
  one_side: concept(
    "o singura parte",
    "one side",
    "Este doar pe o parte",
    "It is only on one side",
    [
      "o singura parte",
      "doar pe o parte",
      "partea stanga",
      "partea dreapta",
      "one side",
      "left side",
      "right side",
    ],
  ),
  speech_trouble: concept(
    "vorbire afectata",
    "speech trouble",
    "Vorbesc greu",
    "I have trouble speaking",
    [
      "probleme de vorbire",
      "vorbesc greu",
      "vorbire neclara",
      "tulburari de vorbire",
      "speech trouble",
      "slurred speech",
      "trouble speaking",
    ],
  ),
  facial_droop: concept(
    "fata cazuta",
    "facial droop",
    "O parte a fetei este cazuta",
    "One side of my face is drooping",
    ["fata cazuta", "gura stramba", "facial droop", "face drooping"],
  ),
  confusion: concept("confuzie", "confusion", "Sunt confuz", "I feel confused", [
    "confuzie",
    "confuz",
    "dezorientat",
    "confusion",
    "confused",
    "disoriented",
  ]),
  fever: concept("febra", "fever", "Am febra", "I have a fever", [
    "febra",
    "temperatura",
    "fever",
    "high temperature",
  ]),
  vomiting: concept("varsaturi", "vomiting", "Am varsaturi", "I am vomiting", [
    "varsaturi",
    "vomit",
    "vomiting",
    "throwing up",
  ]),
  breathing_difficulty: concept(
    "respiratie dificila",
    "breathing difficulty",
    "Respir greu",
    "I have trouble breathing",
    [
      "respir greu",
      "respiratie dificila",
      "lipsa de aer",
      "nu am aer",
      "short of breath",
      "trouble breathing",
      "difficulty breathing",
      "hard to breathe",
    ],
  ),
  fainting: concept("lesin", "fainting", "Am lesinat", "I fainted", [
    "lesin",
    "am lesinat",
    "pierdut cunostinta",
    "fainting",
    "fainted",
    "passed out",
  ]),
  cold_sweats: concept(
    "transpiratii reci",
    "cold sweats",
    "Am transpiratii reci",
    "I have cold sweats",
    ["transpiratii reci", "transpir rece", "cold sweat", "cold sweats"],
  ),
  breathing_at_rest: concept(
    "respiratie dificila in repaus",
    "breathing difficulty at rest",
    "Respir greu si in repaus",
    "Breathing is difficult at rest",
    [
      "respir greu in repaus",
      "respir greu si in repaus",
      "lipsa de aer in repaus",
      "difficult at rest",
      "trouble breathing at rest",
      "short of breath at rest",
    ],
  ),
  blue_lips: concept("buze albastrui", "blue lips", "Am buzele albastrui", "My lips look blue", [
    "buze albastrui",
    "buze albastre",
    "buze vinete",
    "blue lips",
    "bluish lips",
  ]),
  severe_intensity: concept(
    "intensitate foarte mare",
    "very severe intensity",
    "Este foarte intens",
    "It is very intense",
    [
      "foarte intens",
      "foarte tare",
      "sever",
      "insuportabil",
      "very intense",
      "very severe",
      "unbearable",
    ],
  ),
  chills: concept("frisoane", "chills", "Am frisoane", "I have chills", [
    "frisoane",
    "tremur de frig",
    "chills",
    "shivering",
  ]),
  burning_urination: concept(
    "usturime la urinare",
    "burning urination",
    "Ma ustura cand urinez",
    "It burns when I urinate",
    [
      "usturime la urinare",
      "ma ustura cand urinez",
      "ustura la urinare",
      "burning urination",
      "burns when i urinate",
    ],
  ),
  blood_in_urine: concept(
    "sange in urina",
    "blood in urine",
    "Am observat sange in urina",
    "I noticed blood in my urine",
    ["sange in urina", "urina cu sange", "hematurie", "blood in urine", "bloody urine"],
  ),
  nausea: concept("greata", "nausea", "Am greata", "I feel nauseous", [
    "greata",
    "senzatie de voma",
    "nausea",
    "nauseous",
  ]),
  cannot_urinate: concept(
    "imposibilitatea de a urina",
    "inability to urinate",
    "Nu pot urina",
    "I cannot urinate",
    [
      "nu pot urina",
      "nu reusesc sa urinez",
      "cannot urinate",
      "can t urinate",
      "unable to urinate",
    ],
  ),
  chest_pressure: concept(
    "presiune in piept",
    "chest pressure",
    "Simt presiune in piept",
    "I feel chest pressure",
    ["presiune in piept", "apasare in piept", "chest pressure", "pressure in my chest"],
  ),
  breathing_change: concept(
    "schimbare la respiratie",
    "change with breathing",
    "Ma doare mai tare cand respir",
    "It hurts more when I breathe",
    [
      "mai tare cand respir",
      "mai tare cand inspir",
      "se schimba cand respir",
      "la inspiratie",
      "worse when i breathe",
      "hurts when breathing",
      "changes when i breathe",
      "deep breath",
    ],
  ),
  local_tenderness: concept(
    "sensibilitate la atingere",
    "tenderness to touch",
    "Este sensibil la atingere",
    "It is tender to touch",
    [
      "sensibil la atingere",
      "doare la atingere",
      "doare cand ating",
      "tender",
      "tender to touch",
      "hurts when touched",
    ],
  ),
  cold_limb: concept(
    "membru rece",
    "cold limb",
    "Este neobisnuit de rece",
    "It feels unusually cold",
    ["rece", "neobisnuit de rece", "picior rece", "deget rece", "cold", "unusually cold"],
  ),
  pallor: concept("paloare", "pallor", "Pare palid", "It looks pale", [
    "palid",
    "paloare",
    "albicios",
    "pale",
    "pallor",
  ]),
  wound: concept("rana", "wound", "Exista o rana", "There is a wound", [
    "rana",
    "taietura",
    "plaga",
    "wound",
    "cut",
  ]),
  nail_injury: concept(
    "unghie afectata",
    "nail injury",
    "Unghia este afectata",
    "The nail is injured",
    ["unghie afectata", "unghie rupta", "unghie lovita", "nail injury", "damaged nail"],
  ),
  instability: concept(
    "instabilitate",
    "instability",
    "Articulatia este instabila",
    "The joint feels unstable",
    ["instabila", "instabilitate", "fuge articulatia", "unstable", "instability", "gives way"],
  ),
  pain_with_load: concept(
    "durere la contractie sau intindere",
    "pain with contraction or stretch",
    "Doare cand incordez",
    "It hurts when I contract it",
    [
      "doare cand incordez",
      "doare cand intind",
      "creste cand incordez",
      "creste cand intind",
      "hurts when contracting",
      "hurts when stretching",
      "pain with contraction",
      "pain with stretch",
    ],
  ),
  movement_or_posture_change: concept(
    "schimbare la miscare sau postura",
    "change with movement or posture",
    "Se schimba la miscare",
    "It changes with movement",
    [
      "se schimba la miscare",
      "mai rau la miscare",
      "se schimba cu postura",
      "mai rau in anumite pozitii",
      "changes with movement",
      "worse with movement",
      "changes with posture",
      "worse in certain positions",
    ],
  ),
} as const;

export type SemanticConceptId = keyof typeof SEMANTIC_CONCEPTS;

export function conceptTerms(conceptId: SemanticConceptId) {
  return [...SEMANTIC_CONCEPTS[conceptId].terms];
}

export function conceptLabels(conceptIds: readonly SemanticConceptId[], locale: "ro" | "en") {
  return conceptIds.map((conceptId) => SEMANTIC_CONCEPTS[conceptId].label[locale]);
}

export function conceptPlaceholder(conceptIds: readonly SemanticConceptId[]) {
  const conceptId = conceptIds[0];
  if (!conceptId) return undefined;
  return {
    ro: `Ex.: ${SEMANTIC_CONCEPTS[conceptId].example.ro}`,
    en: `E.g. ${SEMANTIC_CONCEPTS[conceptId].example.en}`,
  };
}
